### ISSUE TITLE
Error in loading the plugin

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-discovery-plugin#30]
Couldn't load plugin Discovery due to an error when calling its initGui() method

TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/USER/.qgis2/python/plugins\Discovery\discoveryplugin.py", line 204, in initGui
    self.read_config(config_list[0] if config_list else "")
  File "C:/Users/USER/.qgis2/python/plugins\Discovery\discoveryplugin.py", line 354, in read_config
    connection = settings.value(key + "connection", "", type=str)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.18 Las Palmas, b33566195a

**Comment by saberraz** [comment]
Not reproducible.
