### ISSUE TITLE
Problem po aktualizacji do najnowszej wersji QGIS

### ISSUE THREAD

**Issue by tomjed2023** [lutraconsulting/qgis-discovery-plugin#92]
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/biuro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Discovery\__init__.py", line 16, in classFactory
    return DiscoveryPlugin(iface)
  File "C:\Users/biuro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Discovery\discoveryplugin.py", line 153, in __init__
    self.rubber_band = QgsRubberBand(iface.mapCanvas(), False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

Wersja Pythona: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Wersja QGIS: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533

**Comment by kannes** [comment]
Same as #93 , can be closed
