### ISSUE TITLE
Uncaught TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [lutraconsulting/qgis-discovery-plugin#93]
Impossibile caricare il plugin 'Discovery' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\Discovery\__init__.py", line 16, in classFactory
    return DiscoveryPlugin(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\Discovery\discoveryplugin.py", line 153, in __init__
    self.rubber_band = QgsRubberBand(iface.mapCanvas(), False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

```
Discovery 2.5.7, QGIS 3.30.2-'s-Hertogenbosch on Windows 10

**Comment by kannes** [comment]
Same as #90 , can be closed
