### ISSUE TITLE
Search is no longer functional with geopackage .gpkg

### ISSUE THREAD

**Issue by Martin-GUILLOU** [lutraconsulting/qgis-discovery-plugin#95]
Since version 2.5.8 the search is no longer functional with data stored in geopackage .gpkg.
No error message, the search just returns no results.
The configuration window finds the desired data and fields.
A downgrade to v.2.5.7 is necessary on my side.

QGIS version 3.28.10-Firenze

Desktop OS win 10 pro

Datastore samba Debian

**Comment by DarrenFennell** [comment]
I can second this. I was using this plugin to provide offline address search capability, it used to work great but no longer seems to function despite the config reading the gpkg file, tables and data columns correctly.

QGIS version 3.28.10-Firenze
Desktop OS win 10 enterprise
Datastore OS AddressBase Plus in gpkg format

**Comment by kannes** [comment]
I have a working fix, after testing I will make a PR.

If you want it now, in `discoveryplugin.py` change

        if db is None:
            return

to

        if db is None and self.data_type != "gpkg":
            return

**Comment by OpenSourceMapping** [comment]
I have amended as suggested but get an error message when running a search on a gpkg layer:

WARNING    Traceback (most recent call last):
              File "C:\Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Discovery\discoveryplugin.py", line 376, in on_result_selected
              self.select_result(self.search_results[result_index.row()])
              File "C:\Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Discovery\discoveryplugin.py", line 383, in select_result
              transform = QgsCoordinateTransform(QgsCoordinateReferenceSystem.fromEpsgId(src_epsg),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             TypeError: QgsCoordinateReferenceSystem.fromEpsgId(): argument 1 has unexpected type 'str'

**Comment by kannes** [comment]
I have that fixed too in my branch :) Just waiting for feedback from my client for potential more breakage. Probably some time next week.

The fix for this is changing `fromEpsgId` to `fromOgcWmsCrs`.

Iirc that was all I fixed so far.

**Comment by OpenSourceMapping** [comment]
Thanks, that worked for me,

**Comment by kannes** [comment]
Argh... I will have a look.

**Comment by kannes** [comment]
Here you go: https://github.com/lutraconsulting/qgis-discovery-plugin/pull/104/files

**Comment by OpenSourceMapping** [comment]
I have amended the gpkg_utils.py file and there is still no response for geopackage searches.

**Comment by kannes** [comment]
Hmm, do you have both changes from https://github.com/lutraconsulting/qgis-discovery-plugin/pull/103/files and https://github.com/lutraconsulting/qgis-discovery-plugin/pull/104/files ? Then it *should* work. Try this unofficial ZIP I made with all three of my PRs included: [Discovery_84_95_fix.zip](https://github.com/user-attachments/files/18647533/Discovery_84_95_fix.zip)

**Comment by Martin-GUILLOU** [comment]
> Try this unofficial ZIP I made with all three of my PRs included: [Discovery_84_95_fix.zip](https://github.com/user-attachments/files/18647533/Discovery_84_95_fix.zip)

Thank you, with this version the search is functional again with data stored in geopackage .gpkg.
Good job!

**Comment by kannes** [comment]
Excellent, thanks for testing!

I hope the PRs will be merged soon and packed into a new release :)

**Comment by gregorywaynepower** [comment]
Thanks for the hard work @kannes !

**Comment by OpenSourceMapping** [comment]
Hello @kannes 

Is there any timescale for the new release of the Discovery plugin with this fix?

**Comment by kannes** [comment]
Oh I am the wrong person to ask that as I am just an outside contributor. Maybe @ldebek can answer?
